# Site settings
title: 莫问前程沙漫天
email: zhoujiafeng0116@gmail.com 
description: 珍惜时间
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://JiafengZhou.github.io" # the base hostname & protocol for your site

plugins: 
  - jekyll-paginate
  # - jekyll-feed
  # - jekyll-sitemap
  # - jekyll-seo-tag
  # - jekyll-compose
  # - jekyll-redirect-from

# twitter_username: jekyllrb
github_username: foreverlms
# permalink: /:year/:month/:day/:title/

paginate: 10
paginate_path: "page:num"
# Build settings
markdown: kramdown

# highlight
# use rouge locally, pygments in Github
# highlighter: pygments
# highlighter: rouge
# highlighter: false

timezone: Asia/Shanghai
